name: ianzak
favicon: null
layout_spectrum: 0.38292
typography_spectrum: 0.1505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e151c'
    - '#8ea2a8'
    - '#a2bbc4'
    - '#705d50'
    - '#75888e'
  brandStrength: 0.7059471816755831
  lightness: 0.9375
  saturation: 0.3125
  rhythmicContrast: 0.24879549606703222
purpose: []
