name: ianzak
favicon: null
layout_spectrum: 0.38292
typography_spectrum: 0.1505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#045e69'
    - '#1d8d8f'
    - '#58d0c4'
  brandStrength: 0.7059471816755831
  lightness: 0.9823142238892615
  saturation: 0.05968301370739937
  rhythmicContrast: 0.24879549606703222
purpose: []
